### ISSUE TITLE
&sharpen as a default function?

### ISSUE THREAD

**Issue by flobox** [mosbth/cimage#107]
For some use cases it could be helpful to have "&sharpen" activated by DEFAULT within the config file.
So that images which do NOT contain the operator will still be sharpened?

Looking forward to your opinion on this!

**Comment by mosbth** [comment]
"For some use-cases" - could be elaborated on.

There could be such a setting in the config-file, yes. That would apply to all requests. Perhaps. if one creates a `/img/thumbnail/mikael.png?width=80&crop-to-fit`, one could argue that it would be nice to always supply a default sharpen effect. This implies a special configuration that always creates a thumbnail of a image. 

In general I guess its hard to see that one wants a general default of sharpen since it usually depends on the target size and the original size, "depends". 

So, yes there could be a default setting, if there is a use-case where this is a good thing. Feel free to suggest such a use-case. Perhaps there is a alternate way of achieving the same result.

**Comment by flobox** [comment]
You are right.

I can just point out, what at least we have experienced. The images we are serving do have a pretty hight pixel density. When resizing them we just experienced that the sharpness is mostly not the best.

Before we were using imageresizing.net - we compared the resizing output, the output from imageresizing.net  and the output from cimage. The sharpness when applying a simple resizing (&w=300) was by default a little bit more "friendly" with imageresizing.net. To achieve the same output by cimage we needed to add an exta &sharpen. We experienced for almost all our images. So at least for us, it would be a nice feature, to have the possibilty to turn sharpen on by default in the config file without adding an extra &sharpen to each picture resizing.

By the way!! cimage produced for example 10-12kb pictures in comparison to imageresizing.net with 20kb pictures with the same imageresizing settings and output. So great job here by cimage!!

**Comment by flobox** [comment]
The same for "&quality"...
Default is 60.

For our cases it would be interesting to have an option in the config file, to change the default setting to a value I wish.

**Comment by flobox** [comment]
I have to change my mind here a little bit.

I think you are right and "&sharpen" as a DEFAULT function within the config file might be not the best thing....

Regarding the "&quality" - having the possibilty changing the DEFAULT quality within the config file, I still think this would be a great feature...

**Comment by mosbth** [comment]
Added to configfile fo set own values of default values for jpeg quality and png compression.

```
     /**
      * Change the default values for CImage quality and compression used
      * when saving images.
      *
      * Default value:
      *  jpg_quality:     null, integer between 0-100
      *  png_compression: null, integer between 0-9
      */
      //'jpg_quality'  => 75,
      //'png_compression' => 1,
```
