### ISSUE TITLE
Filename validation doesn't allow Latin characters or other characters such as brackets

### ISSUE THREAD

**Issue by pabloacevedo** [mosbth/cimage#140]
It is really necessary to validate the name of a file if you could actually have a name with any character.

**Comment by mosbth** [comment]
Validation of the characters in the image filename done through a regexp. This setting can be changed in the config-file.
https://github.com/mosbth/cimage/blob/v0.7.9/webroot/img_config.php#L101-L109

Its a rather strict setting from the beginning.

```
'#^[a-z0-9A-Z-/_ \.:]+$#'
```

The check is done in `img.php`:
https://github.com/mosbth/cimage/blob/v0.7.9/webroot/img.php#L422-L423

You can change the setting in in the config-file to allow any type of character in the filename. Perhaps something like this.

```
'#.+#'
```

But, I have not tried it nor have I fully looked into any security related concern that it might introduce. Perhaps none. But I have not checked it.

**I'm pro** in making the default setting more permissive of characters. But I would need to ensure it does not introduce any security concerns.

**Comment by pabloacevedo** [comment]
Thank you very much for your answer.

I'll look a little more about the security risks that can have this change.

**Comment by Hissvard** [comment]
Security issues or not, I think it would be better to return a different status code than a `404 Not Found` when the validation fails, in order for the developer to be able to spot that being the issue at a glance - I didn't think of switching to dev mode at first and it took me a bit to find out the problem was the filename, I kept trying to find errors in the way I was passing the filename in the query string.

Maybe a `422 Unprocessable Entity`?
