### ISSUE TITLE
PDF to Image

### ISSUE THREAD

**Issue by derSteffen** [mosbth/cimage#178]
Is there an option to save a PDF as JPG?

I use the img.php and in my index.php i try `<img src="img.php?src=example.pdf&w=300&q=60&save-as=jpg">`

Thanks for informations.

Greetings

**Comment by mosbth** [comment]
Short answer: No.

To my knowledge is pdf not a supported format for PHP GD, so one need to use alternate tools to make such a conversion possible using `img.php`.

One could use ImageMagick to do the trick, like explained in [this SO post](https://stackoverflow.com/questions/6605006/convert-pdf-to-image-with-high-resolution).

Since `img.php` partly uses ImageMagick for other non essential feature, that might be a way to go, if such a feature would be developed.

**Comment by derSteffen** [comment]
Thanks for your answer :-)
