### ISSUE TITLE
Use imagecreatefromstring() as fallback if no method in \CImage::load() works

### ISSUE THREAD

**Issue by mfn** [mosbth/cimage#85]
Currently `\CImage::load()` is very strict, based on the fileExtension, what type the image must be.

Reality is that images are uploaded with extension `jpg` although they're of `png`, etc.

`imagecreatefromstring()` has auto-detection capability and could be used as a fallback if the standard methods like `imagecreatefromjpeg` fails.

**Comment by mosbth** [comment]
So, the issue is that the image file is named with a not-matching extension and/or has a missing extension, and we still want to try and load that image?

**Comment by mfn** [comment]
The URL e.g. says `http://foo/bar.jpg` but it's type is actually png.

The browser will still render it properly because they autodetection built-in.

`imagecreatefromstring()` also has autodetection built-in and can be used as a falback in such places.

After creating an image with it, one can use `getimagesize()` which will return an array with the index `mime` which is the detected mime-type, e.g. `image/png` in such a case.

**Comment by mosbth** [comment]
I'll do some tests and check it out, both for local images and for remote images.

I guess we are still speaking of, at this stage, only supporting png, jpeg and gif. But nevertheless, I'lll give that some thoughts while checking out the code.

**Comment by mosbth** [comment]
Ok, I'll looked into it and I will do as you suggest, using:

> `imagecreatefromstring()` has auto-detection capability and could be used as a fallback if the standard methods like `imagecreatefromjpeg` fails.

> After creating an image with it, one can use `getimagesize()` which will return an array with the index mime which is the detected mime-type, e.g. image/png in such a case.

In general, this might be a better way of doing it for any type of image, as a default way of loading them, but implementing that would mean several changes since I'm now depending on the file extension throughout  `CImage`.

So, it will be a fix for now, but in the longer run I will most likely change to `imagecreatefromstring()` when loading images and use `getimagesize()` to find out its type.

The result will be that a image can be loaded without a valid extension, or have the wrong extension, and it will still work, if the image is a png, jpeg or gif. I'll wait until later to support more image-types, even if this way of handling loading opens up for that.

**Comment by mfn** [comment]
> In general, this might be a better way of loading any type of image.

You're probably spot on; currently when an image has no extension at all, which in practice occurs, it can't be loaded/transformed/cached either.

**Comment by mosbth** [comment]
Now using `imagecreatefromstring()` to load images. It loads any file that the function feel is a valid image. It was a good suggestion, as it seems.

So this change opened up to support more image formats. But that was not really the intention, it just turned out that way.

Saving images is still only supported for jpg, png, gif. If loading another type of image it will save the image as png. The reason to not support more images is that I'm just to lazy to test the file formats and for myself I only use jpg, png and gif. Its not hard to add support for another image though.

There were some changes all through the code of CImage, so take care when testing. I just put it up on my own website and it seems to work all right.
