### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by nobutsta** [mosbth/cimage#89]
Hello,
I've got the error when I'm call the file:

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in C:\AppServ\www\test\img.php on line 41

Any idea?

**Comment by mosbth** [comment]
How do you call it to produce such an error?
What are the details of your system - use `webroot/check_system.php`.

**Comment by nobutsta** [comment]
I typed in the url : http://localhost/jitta/v1/cimage/img.php?file=photos/2015-03-07-1/sample1200x800.jpg

And this is my system spec.

Current PHP version: 6.0.0-dev

Running on: Apache/2.2.8 (Win32) PHP/6.0.0-dev

Extension gd is loaded.

array(12) {
  ["GD Version"]=>
  string(27) "bundled (2.0.28 compatible)"
  ["FreeType Support"]=>
  bool(true)
  ["FreeType Linkage"]=>
  string(13) "with freetype"
  ["T1Lib Support"]=>
  bool(true)
  ["GIF Read Support"]=>
  bool(true)
  ["GIF Create Support"]=>
  bool(true)
  ["JPG Support"]=>
  bool(true)
  ["PNG Support"]=>
  bool(true)
  ["WBMP Support"]=>
  bool(true)
  ["XPM Support"]=>
  bool(false)
  ["XBM Support"]=>
  bool(true)
  ["JIS-mapped Japanese Font Support"]=>
  bool(false)
}

Extension exif is NOT loaded.
Extension curl is loaded.

Thanks

**Comment by mosbth** [comment]
Correct usage is: 
`http://localhost/git/cimage/webroot/imgd.php?src=car.png`

That is `src` instead of `file`.

The error message (related to anonymous functions) seems a bit out of bound as does the version number. The error message for that line, should not exists if you running PHP 5.3 and above.

My guess is that you have an older release of PHP (<5.3 not supporting). If you are unsure, install the latest PHP version and try again.
